<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PairMeaning;

class PairMeaningSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $rows = [
            ['pair' => '00', 'status' => 'bad', 'short_meaning' => 'มีโลกส่วนตัวสูงมาก เก็บซ่อนอารมณ์และความรู้สึกเก่ง มักมีภาวะเครียดสะสมระวังปัญหาสุขภาพเกี่ยวกับเนื้องอก', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '01', 'status' => 'bad', 'short_meaning' => 'เชื่อมั่นในตนเองสูงเกินไปจนดูเย่อหยิ่ง ทำคุณคนไม่ขึ้น และมักจะถูกคนใกล้ชิดทรยศหักหลังได้ง่าย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '02', 'status' => 'bad', 'short_meaning' => 'มักผิดหวังในความรักและพบเจอปัญหารักซ้อน เป็นคนใจอ่อนขี้สงสารจนถูกหลอกได้ง่าย การเงินรั่วไหลบ่อย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '03', 'status' => 'bad', 'short_meaning' => 'อารมณ์ร้อนรุนแรง ตัดสินใจวู่วาม และมักมีปัญหาขัดแย้งกับผู้อื่นเพราะคำพูดที่ตรงเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '04', 'status' => 'bad', 'short_meaning' => 'มักถูกนินทาให้ร้ายลับหลัง หรือตนเองมักเข้าไปยุ่งเกี่ยวกับความลับของผู้อื่นจนเกิดปัญหา ระวังโรคในช่องท้อง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '05', 'status' => 'bad', 'short_meaning' => 'มีทิฐิสูงและมักขัดแย้งกับผู้ใหญ่หรือผู้ที่มีอำนาจเหนือกว่า ทำให้โอกาสในหน้าที่การงานติดขัด', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '06', 'status' => 'bad', 'short_meaning' => 'ใช้เงินเก่ง สุรุ่ยสุร่าย มักมีปัญหาเรื่องความรักที่ผิดศีลธรรมหรือรักซ้อนที่หาทางออกไม่ได้', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '07', 'status' => 'bad', 'short_meaning' => 'ชีวิตต้องแบกรับภาระหนัก มีความเครียดสูงและต้องต่อสู้ดิ้นรนอย่างเหน็ดเหนื่อยกว่าจะประสบความสำเร็จ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '08', 'status' => 'bad', 'short_meaning' => 'มักลุ่มหลงในอบายมุขหรือการเสี่ยงโชคที่คุมไม่ได้ การเงินพลิกผันรวดเร็ว มีดวงถูกโกงหรือคดีความ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '09', 'status' => 'bad', 'short_meaning' => 'มีโลกส่วนตัวสูงมากจนเข้าถึงยาก มักมีแนวคิดที่ประหลาดไม่เหมือนใคร ทำให้คนรอบข้างมองว่าเข้าสังคมยาก', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '10', 'status' => 'bad', 'short_meaning' => 'ชีวิตมักจะขึ้นๆ ลงๆ ไม่แน่นอน มีความเชื่อมั่นในตัวเองผิดทางจนนำไปสู่ความล้มเหลว', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '11', 'status' => 'bad', 'short_meaning' => 'มีทิฐิสูงมาก ไม่ยอมใคร มักโดดเดี่ยวเพราะความดื้อรั้นของตัวเอง ทำคุณคนไม่ขึ้น', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '12', 'status' => 'bad', 'short_meaning' => 'อารมณ์แปรปรวนเดี๋ยวดีเดี๋ยวร้าย ถูกคนทรยศหักหลังได้ง่าย และมักมีปัญหาสุขภาพเรื่องไมเกรน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '13', 'status' => 'bad', 'short_meaning' => 'ชีวิตมักพบเจออุบัติเหตุหรือเหตุการณ์ที่ต้องผ่าตัดกะทันหัน มีอุปสรรคขวากหนามรุมเร้าตลอดเวลา', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '14', 'status' => 'good', 'short_meaning' => '(มงคล) สติปัญญาดีเยี่ยม เจรจาน่าเชื่อถือ มีผู้ใหญ่คอยให้ความเมตตาและสนับสนุน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '15', 'status' => 'good', 'short_meaning' => '(มงคล) เลขแห่งยอดปัญญาและเมตตามหานิยม ชีวิตมีความสงบสุขและได้รับการอุปถัมภ์ที่ดี', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '16', 'status' => 'bad', 'short_meaning' => 'การเงินรั่วไหล มักมีปัญหาเรื่องความรักที่ซับซ้อน หรือโดนคนใกล้ตัวหลอกเรื่องเงินทอง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '17', 'status' => 'bad', 'short_meaning' => 'มีความเครียดสูง แบกรับความคาดหวังจนเกินตัว มักผิดใจกับผู้ใหญ่เพราะความจริงจังเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '18', 'status' => 'bad', 'short_meaning' => 'มักพบเจอกับการถูกหักหลังและคดีความ การงานมักสะดุดเพราะปัญหาที่ไม่คาดคิด', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '19', 'status' => 'good', 'short_meaning' => '(มงคล) มีความเป็นผู้นำสูง โดดเด่นในสังคม และมักจะได้รับความสำเร็จชื่อเสียง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '20', 'status' => 'bad', 'short_meaning' => 'มักคิดเพ้อฝันเกินจริง จับจด ทำอะไรไม่สำเร็จเป็นชิ้นเป็นอัน และมีปัญหาเรื่องเงินทองรั่วไหล', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '21', 'status' => 'bad', 'short_meaning' => 'ทำคุณคนไม่ขึ้น มักถูกเบียดเบียนหรือเอาเปรียบจากคนที่ไวใจ ชีวิตต้องสู้เพียงลำพัง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '22', 'status' => 'good', 'short_meaning' => 'มีเสน่ห์ที่อ่อนโยน จิตใจดี มีความเห็นอกเห็นใจผู้อื่น ส่งเสริมด้านความเมตตาปรานี', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '23', 'status' => 'good', 'short_meaning' => 'มีเสน่ห์แรงและมีความกล้าได้กล้าเสีย ไหวพริบดี แก้ปัญหาเฉพาะหน้าได้อย่างยอดเยี่ยม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '24', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) เมตตามหานิยมขั้นสูง พูดจาเป็นเงินเป็นทอง มีผู้อุปถัมภ์และโชคลาภดีเยี่ยม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '25', 'status' => 'good', 'short_meaning' => 'มีสติปัญญาดี รู้จักใช้เหตุผลควบคู่กับอารมณ์ มักได้รับโชคและความสำเร็จจากผู้ใหญ่', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '26', 'status' => 'good', 'short_meaning' => 'รสนิยมดี มีเสน่ห์ในการพูดจาอ่อนหวาน หาเงินเก่งและรักความสะดวกสบาย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '27', 'status' => 'bad', 'short_meaning' => 'แบกรับภาระหนี้สินหรือความเครียดรุนแรง ชีวิตต้องดิ้นรนและเผชิญกับอุปสรรคต่อเนื่อง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '28', 'status' => 'bad', 'short_meaning' => '(กาลกิณีท้าย) ใจใหญ่ กล้าเสี่ยงในทางที่ผิด พลิกผันง่ายและมีดวงถูกโกงหรือมีคดีความ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '29', 'status' => 'good', 'short_meaning' => 'มีจินตนาการสูง ความคิดสร้างสรรค์ดีเยี่ยม และมักจะได้รับเกียรติหรือชื่อเสียงในสังคม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '30', 'status' => 'bad', 'short_meaning' => 'มักพบเจอเหตุการณ์ร้ายกะทันหัน หรือมีปัญหาแฝงเร้นที่หาทางออกยาก ความเครียดสะสม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '31', 'status' => 'bad', 'short_meaning' => 'เหน็ดเหนื่อยกับการทำงานหนักแต่ผลลัพธ์ไม่คุ้มค่า มีอุปสรรคขัดขวางความก้าวหน้าเสมอ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '32', 'status' => 'good', 'short_meaning' => 'มีเสน่ห์ดึงดูดผู้อื่นและมีคนคอยช่วยเหลืออุปถัมภ์ดีเยี่ยม การงานเจริญรุ่งเรือง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '33', 'status' => 'conditional', 'short_meaning' => 'พลังงานสูงมาก กล้าหาญ ขยัน แต่ควรระวังอารมณ์ร้อนและการตัดสินใจที่วู่วาม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '34', 'status' => 'bad', 'short_meaning' => 'คำพูดนำภัยมาสู่ตัว มีความขัดแย้งกับคนรอบข้างได้ง่ายเพราะการเจรจาที่รุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '35', 'status' => 'good', 'short_meaning' => '(มงคล) มีบารมีและภาวะผู้นำ ผู้ใหญ่ให้ความเมตตาและลูกน้องเกรงใจ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '36', 'status' => 'good', 'short_meaning' => '(มงคล) เด่นเรื่องเสน่ห์และการเงิน มีโชคลาภและผู้อุปถัมภ์สนับสนุนในทุกด้าน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '37', 'status' => 'bad', 'short_meaning' => 'เครียดจัด ภาระหนักหนาสาหัส และเสี่ยงต่ออุบัติเหตุหรือการผ่าตัดกะทันหัน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '38', 'status' => 'bad', 'short_meaning' => 'หลงเชื่อคนผิดได้ง่าย มักถูกชักจูงไปในทางที่เสื่อมเสีย หรือมีดวงถูกโกงรุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '39', 'status' => 'good', 'short_meaning' => 'มีโชคด้านชัยชนะและการแข่งขัน ประสบความสำเร็จอย่างรวดเร็วและมีความก้าวหน้าที่โดดเด่น', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '40', 'status' => 'bad', 'short_meaning' => 'มักมีเรื่องอื้อฉาวหรือความลับถูกเปิดเผย ชีวิตมีความยุ่งเหยิงและปัญหาที่อธิบายยาก', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '41', 'status' => 'good', 'short_meaning' => 'สติปัญญาเฉลียวฉลาด มีไหวพริบในการเจรจา และได้รับความเมตตาจากผู้ใหญ่เสมอ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '42', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีเสน่ห์ เมตตามหานิยม พูดจาเป็นเงินเป็นทอง ดึงดูดโชคลาภดีเยี่ยม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '43', 'status' => 'bad', 'short_meaning' => 'มักเกิดการโต้เถียงขัดแย้ง และมีเกณฑ์เกิดอุบัติเหตุหรือปัญหาจากการตัดสินใจวู่วาม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '44', 'status' => 'good', 'short_meaning' => 'ไหวพริบปฏิภาณว่องไว ทันสมัย ทันโลก และมีทักษะในการสื่อสารที่ทรงพลัง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '45', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) เลขแห่งยอดปัญญา มีหลักการและเหตุผล เป็นที่ยอมรับนับถือของคนทุกระดับ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '46', 'status' => 'good', 'short_meaning' => 'มีรสนิยมดี มีเสน่ห์ในการหาเงินและการใช้ชีวิต มีโชคลาภด้านความรักและทรัพย์สิน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '47', 'status' => 'bad', 'short_meaning' => 'เหน็ดเหนื่อยกับการทำงานหนักแต่ผลตอบแทนน้อย มีความเครียดเรื่องภาระหน้าที่สูง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '48', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักหลงเชื่อคนผิด หรือถูกชักจูงไปในทางที่เสื่อมเสีย มีดวงถูกโกงรุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '49', 'status' => 'bad', 'short_meaning' => 'ชีวิตผันผวนรวดเร็วเกินไป มักเกิดเหตุการณ์ร้ายกะทันหันหรืออุบัติเหตุที่คาดไม่ถึง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '50', 'status' => 'good', 'short_meaning' => 'มีโชคลาภจากการเดินทางหรือการติดต่อต่างประเทศ สนใจเทคโนโลยีและสิ่งใหม่ๆ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '51', 'status' => 'good', 'short_meaning' => '(มงคล) มีปัญญาเลิศ ผู้ใหญ่เมตตาเอ็นดู ชีวิตมีความสุขสมบูรณ์และมั่นคง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '52', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักมีปัญหาเรื่องความรักซับซ้อน หรือโดนคนใกล้ตัวเอาเปรียบเรื่องการเงิน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '53', 'status' => 'bad', 'short_meaning' => 'มักมีความขัดแย้งกับผู้ใหญ่หรือหัวหน้างาน หน้าที่การงานมักสะดุดเพราะทิฐิสูง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '54', 'status' => 'good', 'short_meaning' => '(มงคล) สติปัญญาเฉลียวฉลาด มีหลักการน่าเชื่อถือ และได้รับโอกาสดีๆ จากผู้ใหญ่', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '55', 'status' => 'good', 'short_meaning' => 'ชีวิตมีความสงบสุข มั่นคง มีคุณธรรมสูง และมักจะได้รับความสำเร็จแบบค่อยเป็นค่อยไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '56', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) บริหารจัดการการเงินและงานได้ดีเยี่ยม มีโชคลาภและความสำเร็จที่สมบูรณ์', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '57', 'status' => 'bad', 'short_meaning' => 'มีความเครียดสูง ดื้อรั้น และมักจะขัดแย้งกับผู้อื่นเพราะความคิดที่ตึงเครียดเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '58', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักถูกหลอกลวงหรือเข้าไปพัวพันกับสิ่งไม่ดี ชีวิตมีความวุ่นวายเรื่องการเงิน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '59', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) มีสิ่งศักดิ์สิทธิ์คุ้มครอง ลางสังหรณ์แม่นยำ และมีโชคจากการเดินทางต่างประเทศ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '60', 'status' => 'good', 'short_meaning' => 'มีสุนทรียภาพในชีวิต รสนิยมดี และมีความสุขกับการหาความเพลิดเพลินให้ตนเอง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '61', 'status' => 'bad', 'short_meaning' => 'การเงินรั่วไหล มักมีปัญหาเรื่องความรักที่ซับซ้อน หรือโดนคนใกล้ตัวเอาเปรียบ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '62', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีเสน่ห์ในการพูดจาอ่อนหวาน รสนิยมดี และหาเงินเก่ง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '63', 'status' => 'good', 'short_meaning' => '(มงคล) มีโชคด้านความรักและการเงิน ประสบความสำเร็จอย่างรวดเร็ว', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '64', 'status' => 'good', 'short_meaning' => '(มงคล) รสนิยมดี มีเสน่ห์ในการหาเงิน และมีความคิดสร้างสรรค์ที่โดดเด่น', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '65', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) บริหารจัดการชีวิตได้ดีเยี่ยม มีความสุขสมบูรณ์ทั้งการงานและการเงิน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '66', 'status' => 'good', 'short_meaning' => 'รักความสนุกสนาน มีโชคลาภด้านความบันเทิงและการกินดื่ม มีเสน่ห์ล้นเหลือ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '67', 'status' => 'bad', 'short_meaning' => 'แบกรับภาระหนี้สินและความเครียดรุนแรง ชีวิตต้องดิ้นรนและเผชิญกับอุปสรรค', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '68', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) การเงินพลิกผันรวดเร็ว มักลุ่มหลงในอบายมุขหรือการเสี่ยงโชคที่คุมไม่ได้', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '69', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีเสน่ห์ดึงดูดและมีการหมุนเวียนของพลังงานที่ดี ลางสังหรณ์แม่นยำ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '70', 'status' => 'bad', 'short_meaning' => 'มีความเครียดสะสมและมักพบเจอกับปัญหาเก่าๆ ที่ตามมาหลอกหลอน ระวังปัญหาสุขภาพ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '71', 'status' => 'bad', 'short_meaning' => 'แบกรับภาระหน้าที่หนักเกินตัว มีความเครียดสูงและมักถูกกดดันจากผู้ใหญ่', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '72', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักมีปัญหาเรื่องหนี้สินที่พัวพันยาวนาน หรือความรักที่สร้างความทุกข์ระทม', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '73', 'status' => 'bad', 'short_meaning' => 'ชีวิตมักพบเจออุบัติเหตุ อุปสรรคขวากหนาม และการแตกหักที่กะทันหัน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '74', 'status' => 'conditional', 'short_meaning' => '(สีเหลือง) จริงจังกับการทำงานมาก มีไหวพริบในการแก้ปัญหาแต่อาจจะเครียดเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '75', 'status' => 'bad', 'short_meaning' => 'มักมีความขัดแย้งกับผู้ใหญ่หรือกฎระเบียบ หน้าที่การงานมักสะดุดเพราะทิฐิสูง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '76', 'status' => 'bad', 'short_meaning' => 'ชีวิตเต็มไปด้วยภาระและความเหนื่อยยาก การเงินรั่วไหลและมีปัญหาเรื่องความรัก', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '77', 'status' => 'bad', 'short_meaning' => '(เครียดคูณสอง) แบกภาระหนักอึ้ง อุปสรรครุมเร้า และต้องรอคอยความสำเร็จนานเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '78', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักเข้าไปพัวพันกับธุรกิจเสี่ยงหรืออบายมุข มีดวงถูกโกงหรือมีคดีความรุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '79', 'status' => 'good', 'short_meaning' => 'มีความอดทนสูง สติปัญญาดีในเชิงลึก สนใจเทคโนโลยีสมัยใหม่หรือศาสตร์เร้นลับ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '80', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มีปัญหาแฝงเร้นที่บอกใครไม่ได้ มักมีดวงถูกหักหลังหรือพบเหตุร้ายกะทันหัน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '81', 'status' => 'bad', 'short_meaning' => 'มักถูกหักหลังและมีปัญหาขัดแย้งกับผู้ใหญ่ หน้าที่การงานมักสะดุด', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '82', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีเสน่ห์แรงดึงดูด ดึงดูดเงินก้อนโตและโชคลาภกะทันหัน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '83', 'status' => 'bad', 'short_meaning' => 'อารมณ์ร้อนรุนแรง กล้าได้กล้าเสียเกินไป และเสี่ยงต่ออุบัติเหตุรุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '84', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มักถูกนินทาให้ร้าย หรือเข้าไปพัวพันกับข่าวอื้อฉาวและธุรกิจสีเทา', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '85', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) มีทิฐิสูงและมักขัดแย้งกับระเบียบหรือศีลธรรม หน้าที่การงานสะดุด', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '86', 'status' => 'bad', 'short_meaning' => 'ใช้เงินเก่ง สุรุ่ยสุร่าย มักลุ่มหลงในอบายมุขและความสวยงามที่เกินกำลัง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '87', 'status' => 'bad', 'short_meaning' => 'แบกภาระหนักอึ้ง มีหนี้สินล้นตัว และต้องต่อสู้ดิ้นรนอย่างเหน็ดเหนื่อย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '88', 'status' => 'bad', 'short_meaning' => '(ห้ามลงท้าย) ใจใหญ่ กล้าเสี่ยงในทางที่อันตราย และเสี่ยงต่อการถูกโกงรุนแรง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '89', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีสิ่งศักดิ์สิทธิ์คุ้มครอง ลางสังหรณ์แม่นยำ และมีอำนาจบารมีสูง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '90', 'status' => 'bad', 'short_meaning' => 'มีโลกส่วนตัวสูงจนเข้าถึงยาก มักคิดวิตกกังวลและจมอยู่กับเรื่องราวเร้นลับเกินไป', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '91', 'status' => 'good', 'short_meaning' => 'มีความเป็นผู้นำโดดเด่น ชื่อเสียงดี และมีโชคลาภจากการติดต่อต่างแดน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '92', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) จินตนาการสูง มีเสน่ห์อ่อนโยน และมีลางสังหรณ์ที่ช่วยเรื่องเงิน', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '93', 'status' => 'good', 'short_meaning' => 'มีโชคด้านชัยชนะ ประสบความสำเร็จจากการแข่งขัน และแคล้วคลาดปลอดภัย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '94', 'status' => 'good', 'short_meaning' => 'มีพรสวรรค์ในการสื่อสารที่ทรงพลัง มีไหวพริบทันสมัย และลางสังหรณ์แม่นยำ', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '95', 'status' => 'good', 'short_meaning' => '(มงคลยิ่ง) ยอดปัญญา มีสิ่งศักดิ์สิทธิ์คุ้มครอง และได้รับความสำเร็จที่มั่นคง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '96', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) รสนิยมดี มีเสน่ห์ในการหาเงิน และมีความสุขกับการใช้ชีวิต', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '97', 'status' => 'good', 'short_meaning' => 'มีความอดทนสูง สติปัญญาดีในเชิงลึก และสนใจนวัตกรรมสมัยใหม่', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '98', 'status' => 'good', 'short_meaning' => '(ห้ามลงท้าย) มีพลังอำนาจที่มองไม่เห็นคุ้มครอง โชคลาภกะทันหัน และใจคอกว้างขวาง', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
            ['pair' => '99', 'status' => 'good', 'short_meaning' => '(มงคลสูงสุด) สิ่งศักดิ์สิทธิ์คุ้มครองหนุนนำ ลางสังหรณ์แม่นยำ แคล้วคลาดปลอดภัย', 'long_meaning' => null, 'created_at' => $now, 'updated_at' => $now],
        ];

        PairMeaning::upsert($rows, ['pair'], ['status', 'short_meaning', 'long_meaning', 'updated_at']);
    }
}
