# 🚀 Triggering first automated deployment with secrets...
name: 🚀 Auto Deploy via FTP

on:
  push:
    branches:
      - prepaid-flow  # ทำงานเฉพาะตอนที่เรา push ขึ้น branch นี้

jobs:
  web-deploy:
    name: 🎉 Deploying to Pathosting
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files to Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /domains/supernumber.co.th/public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/tests/**
          **/storage/*.pdf
          .github/workflows/**
          README.md
          composer.json
          composer.lock
          package.json
          package-lock.json
          webpack.mix.js
          vite.config.js
